### ISSUE TITLE
list of objects bug

### ISSUE THREAD

**Issue by stevekrouse** [funkia/turbine#100]
I've found a strange bug at the intersection of 

1. Stateful behavior (`yield liftNow(sample(scan(...)))`): the bug goes away for a constant `Behavior.of([{ num: 0 }, { num: 1 }])`
2. A Behavior of a list of objects: the bug goes away on a stateful Behavior of a list of strings `["1", "2"]` ([as shown here](https://codesandbox.io/s/7m851zl5o0))
3. The `list` function: the bug goes away for `div(names.map(x => JSON.stringify(x))`

In short, the `list` function breaks when the `div` function works just fine. You can see for yourself here by clicking the "create" button and seeing the new elements in the JSON (for debugging purposes) but not the list below: https://codesandbox.io/s/nkx7xmpj0p

```javascript
function liftNow(now) {
  return modelView(() => now, () => emptyComponent)();
}

const crud = function*() {
  const { click } = yield button("Create");
  const names = yield liftNow(
    sample(
      scan(
        (newName, l) => l.concat({ num: l.length }),
        [{ num: 0 }, { num: 1 }],
        click
      )
    )
  );
  yield div(names.map(x => JSON.stringify(x)));

  yield list(x => div(x.num), names);
};

runComponent("#app", crud);
```

**Comment by paldepind** [comment]
This should fix it

```diff
-   yield list(x => div(x.num), names);
+   yield list(x => div(x.num), names, x => x.num);
```

#101 should (ideally) explain why this is necessary.

**Comment by paldepind** [comment]
I'm closing this as it doesn't appear to be a bug.
