### ISSUE TITLE
How to declare attributes

### ISSUE THREAD

**Issue by paldepind** [funkia/turbine#58]
This issue is meant to be a continuation of the discussion about attributes that began in #48.

The problem is that when creating an element with attributes you currently have to give them in an `attrs` property.

```js
input({attrs: {placeholder: "Foo"}});
```

This makes declaring attributes slightly more verbose than if they could be given directly on the object. This choice was made to keep attributes separate from [all the other things](https://github.com/funkia/turbine/blob/master/src/dom-builder.ts#L64) that one can specify on the object to an HTML element function.

This PR is meant to explore if there is a way to make attributes less verbose without sacrificing other qualities.

**Comment by paldepind** [comment]
@dmitriz 

> Is that an advantage because otherwise there is some danger that they clash? For instance, if `placehoder` is declared directly on the node, is there any potential problem? For instance, the `output` or other prop is also set directly on the node but I've thought there would be no confusion with attributes, since there is no attributes with that names. 

Yes. Clashing could occur. At a conceptual level I think there's something "clean" about having attributes clearly marked as attributes and not mixed together with other special things in the framework.

I think @trusktr's idea of prefixing with an underscore is interesting. I think it's similar to how Angular prefixes their special attributes with `ng-` and how Vue uses `v-`.

**Comment by paldepind** [comment]
#19 about a fancy dsl for creating elements may be relevant.

**Comment by paldepind** [comment]
@trusktr

> WHat about maybe chaining the API instead of an object?
>
> ```js
> const name = yield input({placeholder: 'name'})
>   .output('value')
>   .classToggle('foo', behavior)
>   .classToggle({bar: behavior2, baz: behavior3})
> 
>  // pass `name` along here like before, for example
>  ```

That's an interesting idea 👍 

I think adding an `output` method to `Component` is something we need to do in any case. Because then you can change the output of custom user created components without all of them having to deal with an `output` property.

But, maybe having everything as methods can make things harder to read because the properties describing the HTML are spread across several objects?

> Would that be too imperative?

As long as the methods are still pure (i.e. don't mutate the component) there's nothing imperative about it 😄

**Comment by dmitriz** [comment]
@paldepind 

> Yes. Clashing could occur. At a conceptual level I think there's something "clean" about having attributes clearly marked as attributes and not mixed together with other special things in the framework.

That sounds mysterious to me ;)
Not sure I understand the practical implications.

There are also props, and couple of other categories,
so remembering which one is where may add some overhead,
also to the maintainer who have to decide each time where things go,
and possibly change from version to version, introducing more api,
as opposed to the simple flat structure where there is no api,
no maintenance cost and the user does not have to think.

Another reason is, flat is precisely the way it is handled by the html,
so there is no context switch.
At least for myself, I would like to see if there are 
any concrete examples demonstrating any serious disadvantages.

**Comment by dmitriz** [comment]
@trusktr

I like it too and was playing myself with the idea write  any attribute in the fluent style, i.e.

```js
tag({ attribute: name })
```
is identical to
```js
tag.attribute(name)
```

That makes it easy to remember. 

Also, 
```js
const { inputValue } = input()
```
assumes the attribute `inputValue` on the `input` I suppose?

Another crazy but convenient thing would be to declare the outputs inline without and extra line:

```js
div([
    const { inputValue } = input(),
    div(`Hello ${inputValue}`)
])
```

**Comment by paldepind** [comment]
After #72 one can simply declare attributes as

```js
input({placeholder: "Foo", anotherAttribute: "bar"});
```
