### ISSUE TITLE
Confused by all the output options

### ISSUE THREAD

**Issue by stevekrouse** [funkia/turbine#87]
I'm very confused by the various styles of output:

```javascript
// 1
const counterView = ({ count }) =>
  div([
  "Counter ",
  count,
    button("+").output({ incrementClick: "click" }),
]);

// 2
const counterView = ({ count }) =>
  div([
    h2("Counter"),
    count,
    button({ output: { incrementClick: "click" } }, "Count")
  ]);

 // 3
const counterView = go(function*({ count }) {
  const {click: incrementClick} = yield button("Count")
  yield text(count)
  return { incrementClick }
})
```

Are some older styles that still work or are some fully depreciated? It'd probably go a long way towards my sanity if I knew which was the preferred way. (Unless they are not fully equivalent in which case I'd be curious to know the trade-offs of each style.)

**Comment by paldepind** [comment]
Option 1 and 2 does exactly the same. In the latest version of Turbine option 2 was removed. Essentially all the inbuilt HTML element functions in Turbine accepted an `output` property on their input object with the same behavior as using the `output` method on components. We removed it to

* Make things simpler
* Increase consistency between the "inbuilt" components and the components a user creates himself which , unless the user explicitly does the work, does not handle an `output` property.

As for option 3. Using generator function corresponds to invocations to the `chain` method (similarly to how do-notation in Haskell corresponds to invocations of the `>>=` operator). We've tried to [explain it in the documentation](https://github.com/funkia/turbine#understanding-generator-functions). If that is unclear please let me know. With that in mind I think the question is: what is the difference between the `output` method and the `chain` method? I think that will take a slightly longer explanation. I will get back to you with that :smile:

**Comment by stevekrouse** [comment]
Ok, so version 2 is gone and dead. Are 1 and 3 equivalent? 

I understand that `chain` is bind (`>>=`) in Haskell or `then` in JS. So how does `output` correspond to Haskell?

I guess this relates to my question #93 on `go and `fgo`

**Comment by paldepind** [comment]
Did the explanation above help you @stevekrouse?

**Comment by stevekrouse** [comment]
This all makes sense. I sometimes have trouble getting Option 3 working correctly, but I guess that's less recommended/supported....

**Comment by paldepind** [comment]
It seems that this issue can be closed now. Option 2 has since been removed in favor of always using option 1 instead. So I guess that improves the situation. Option 3 still works but it's probably more advanced usage and probably not something that a new user would have to even know about.
