### ISSUE TITLE
Issues with lift

### ISSUE THREAD

**Issue by stevekrouse** [funkia/turbine#88]
(I made this issue in Turbine because that's where I'm trying to use `lift` but I can move this to `jabz` if you prefer...)

1. Do I import it from `jabz` and do `lift(f, b1, b2)`? Or I use it as `b1.lift(f, b2)`? It seems like most `jabz` things are importable from `hareactive` but not lift. Why is that?

2. `lift` doesn't seem to work for 4 behaviors but the documentation says "You can also combine in this fashion any number of behaviors"

3. `lift` doesn't work with `loop` parameters in the second argument spot with error `this.fn.last is not a function`:

https://codesandbox.io/s/p56qm7lkwj

```javascript
const timer = loop(
  ({ x }) =>
    function*() {
      const x_ = Behavior.of(1);
      // works
      yield div(lift((a, b) => a + " " + b, Behavior.of(3), x));

      // does not work
      yield div(lift((a,b) => a + " " + b, x, Behavior.of(3)));

      return { x: x_ };
    }
);
```

**Comment by paldepind** [comment]
> Do I import it from jabz and do lift(f, b1, b2)? Or I use it as b1.lift(f, b2)? It seems like most jabz things are importable from hareactive but not lift. Why is that?

That's an omission. Hareactive is supposed to be self contained. Jabz is only an optional library that Hareactive intends to play nice with but it should not be required. https://github.com/funkia/hareactive/commit/f273a1a9cc3b3824afbf5a7e680e61b13e3f2644 fixes that. Now Hareactive exports its own `lift` function.

Both 2 and 3 looks like bugs to me.

**Comment by stevekrouse** [comment]
Ok, thanks! Did your recent commit also try to fix the bugs 2 and 3?

**Comment by paldepind** [comment]
https://github.com/funkia/hareactive/commit/2f4c3331abc1da257d6f1d46a83a10c313d9ea7f should fix bug nr. 3.
