### ISSUE TITLE
Constructors in the API documentation

### ISSUE THREAD

**Issue by stevekrouse** [funkia/turbine#89]
I find constructors very useful, particularly in creating mock code or to do sanity checks to test what's wrong, yet the only way I found them is by going into the `test/` of each project. I would love these to be in the documentation for each project:

```javascript
Behavior.of
Future.of
IO.of
```

(Let me know if you'd like me to tackle this one.)

**Comment by paldepind** [comment]
Yes. I definitely agree. These should be documented. If you'd like to do a pull request that'd be really nice. I think they should be documented in the Hareactive documentation though.

Another function that is very useful for similar reasons, but also undocumented, is `empty : Stream<any>`. It's simply an empty stream.

**Comment by stevekrouse** [comment]
I'm on it!

**Comment by stevekrouse** [comment]
Done!

https://github.com/funkia/hareactive/pull/55
https://github.com/funkia/io/pull/1
